### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by dgrala** [asottile/gh-perf-review#11]
I have a token with the "repo" permissions.

Getting permissions error:
```
.HTTPError 422 Unprocessable Entity.
{
    "message": "Validation Failed",
    "errors": [
        {
            "message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",
            "resource": "Search",
            "field": "q",
            "code": "invalid"
        }
    ],
    "documentation_url": "https://developer.github.com/v3/search/"
}
```

The query used by the script was `org%3Alyft%20is%3Apr%20is%3Amerged%20author%3Adgrala%20merged%3A2019-01-01..2019-12-31`

**Comment by asottile** [comment]
sounds like you didn't follow the [directions](https://github.com/asottile/gh-perf-review#setting-up-a-token) for setting up a token properly

**Comment by dgrala** [comment]
Seems like the SSO interface is not very intuitive. Figured it out - closing, thanks!

**Comment by asottile** [comment]
cheers!
